name: Python application test with pytest and pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker environment
      run: docker-compose -f docker-compose.yaml up --build -d

    - name: List Docker containers
      run: docker ps

    - name: Run pytest in Docker
      run: docker-compose exec -T backend pytest --cov --cov-report=html:coverage_html

    - name: Copy coverage reports from Docker container
      run: docker cp $(docker-compose ps -q backend):/app/coverage_html ./coverage_html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage_html

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov

    - name: Check Python code style with Pylint on fsm.py
      run: |
        pylint fsm.py || true
        echo "Pylint check completed."

    - name: Shutdown Docker Compose
      run: docker-compose down
